package cz.muni.fi.DebugDbAnalyzerApp.Application;

import java.awt.BorderLayout;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Miroslav Kubus
 */
public class AnalyzerApp extends javax.swing.JFrame {

    /**
     * Creates new form AnalyzerApp
     */
    public AnalyzerApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        editJMenu = new javax.swing.JMenu();
        editPathJMenuItem = new javax.swing.JMenuItem();
        helpJMenu = new javax.swing.JMenu();
        manualJMenuItem = new javax.swing.JMenuItem();
        creditsJMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");
        jMenuBar.add(jMenu1);

        editJMenu.setText("Edit");

        editPathJMenuItem.setText("Output paths");
        editJMenu.add(editPathJMenuItem);

        jMenuBar.add(editJMenu);

        helpJMenu.setText("Help");

        manualJMenuItem.setText("Manual");
        manualJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manualJMenuItemActionPerformed(evt);
            }
        });
        helpJMenu.add(manualJMenuItem);

        creditsJMenuItem.setText("Credits");
        creditsJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditsJMenuItemActionPerformed(evt);
            }
        });
        helpJMenu.add(creditsJMenuItem);

        jMenuBar.add(helpJMenu);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manualJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manualJMenuItemActionPerformed
        JFrame manualFrame = new JFrame();
        manualFrame.setTitle("How to use database analyzer");
        
        JLabel manual = new JLabel();
        String text = "<b>Debug database analyzer.</b><br> <br>"
                + "Application analyses debug database. It creates <br>"
                + "index on process_name attribute in debug_log table <br>"
                + "in chosen database for more effective data loading. <br> <br>"
                + "Application loads data from database, calculates statistics <br> "
                + "and performs aggregation according to value of info attribute. <br> <br>"
                + "Output is visualized in <b> default browser for html files. </b> <br> <br>"
                + "<b>To run application select path to debug database <br> "
                + "and click analyze. It is possible to turn on filtering.<b>";
        
        setUpJLabel(manual, 18.0f, text);
        addComponentToFrame(manualFrame, manual, 600, 400);
    }//GEN-LAST:event_manualJMenuItemActionPerformed

    private void creditsJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditsJMenuItemActionPerformed
        JFrame creditFrame = new JFrame();
        creditFrame.setTitle("About database analyzer");
        
        JLabel info = new JLabel();
        String text = "<b>Debug database analyzer.</b><br> <br>"
                + "Application created as a part of bachelor thesis. <br>"
                + "It is used as a tool for troubleshooting of processes. <br> <br>"
                + "Miroslav Kubus <br> Masaryk University, Faculty of Informatics"; 
        
        setUpJLabel(info, 20.0f, text);
        addComponentToFrame(creditFrame, info, 500, 300);
    }//GEN-LAST:event_creditsJMenuItemActionPerformed

    private void setUpJLabel(JLabel label, float fontSize, String text) {
        label.setHorizontalAlignment(JLabel.CENTER);
        label.setText("<html><div style='text-align: center;'>" + text + "</div></html>");
        label.setFont(label.getFont().deriveFont(fontSize));
    }
    
    private void addComponentToFrame(JFrame frame, JComponent component, int xSize, int ySize) {
        frame.add(component, BorderLayout.CENTER);
        frame.pack();
        frame.setSize(xSize, ySize);
        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        frame.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnalyzerApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnalyzerApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnalyzerApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnalyzerApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnalyzerApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem creditsJMenuItem;
    private javax.swing.JMenu editJMenu;
    private javax.swing.JMenuItem editPathJMenuItem;
    private javax.swing.JMenu helpJMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem manualJMenuItem;
    // End of variables declaration//GEN-END:variables
}
